### ISSUE TITLE
Collection::gatherDisplayEntities cloning prior to knowing if the entity matches filter.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [bjnortier/dxf#11]
Just something I noticed, the insert block primitive forEach uses cloneDeep on the entity even if it is not included in the displayEntities output by the layers filter passed in as an argument.

No harm done really, but it seems like something that should be executed after the filter condition is met.

**Comment by bjnortier** [comment]
Closed since gatherDisplayEntities no longer exists
