### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ColmMcBarron** [bjnortier/dxf#12]
Is it possible to provide some more documentation, at present it say to look in the test/functional folder for examples but there are none there.

I'm digging through unit tests and code to try to figure out how it works.

**Comment by bjnortier** [comment]
Hi, yes, sure. Definitely needed. I've been working on this quite a bit on the last week or two and things are more stable now.

Can't you see test/functional/svgentities.test.js though?

This takes the examples .DXF files and creates SVGs for them

**Comment by bjnortier** [comment]
I've added some examples under examples/ and updated the README. Can you have a look and let me know what's still unclear/needs explaining?

**Comment by ColmMcBarron** [comment]
Much better, those were the bits I was looking for -- thanks!
