### ISSUE TITLE
Hatch with polyline points only returning y coordinate

### ISSUE THREAD

**Issue by mstigter0** [bjnortier/dxf#130]
Hi,

I've got an issue with parsing hatches with polyline points (only y values are returned). 
![image](https://user-images.githubusercontent.com/57939735/225312025-6bd4037b-529b-4d99-bfaa-685007ed67d7.png)

I've found that removing the Object.create() and just setting polypoints to the object fixes my issue but i dont know if this creates other issues. 
I saw that this line was added in a commit that added the bulge to the polypoints (879808c).
https://github.com/skymakerolof/dxf/blob/72302c5ca3e62721b805725aad105eb7f12b4d2e/src/handlers/entity/hatch.js#L30-L34
![image](https://user-images.githubusercontent.com/57939735/225312346-2611a95a-5aef-409e-8202-42937e961783.png)

I cant see why Object.create(0 doesnt work so would appriciate it if this is looked at.

**Comment by Akbar1909** [comment]
The same result on my side

**Comment by stevage** [comment]
Yes, I found the same thing. And the fix suggested works for me.

I'm not sure why `Object.create()` is used here (and in a few other places) but it definitely looks wrong. I think what is happening is:

1. `polyPoint` is initialised with a value of `{}` (and a prototype that includes values for `x`, `y` and `bulge`)
2. `polyPoint.y` is given a value
3. ...that's it. So when `polyPoint` (now inside an array) is returned later on, it has just a `y` property.
