### ISSUE TITLE
Documentation or examples to make this library work in the browser

### ISSUE THREAD

**Issue by goatchurchprime** [bjnortier/dxf#19]
The README.md advertises that this will also be for the browser, but there is no further information, and  none of the .js files look suitable for inclusion into the browser.   

Having scratched my head with someone who knows more about node than I do (ie he knows more than nothing), we can get something to run in the browser, like so:

**test2.js:**
```
const dxf = require('..')
exports.dxf = dxf; 
```
Then the command:
`browserify test2.js --standalone bdxf -o examples/bundledxf.js
`
And then it's possible to access the dxf parser the following code in an html page:
```
<script type="text/javascript" src="bundledxftrial.js"></script>
<script>var k = "some DXF content";    
var h = bdxf.dxf.parseString(k); 
console.log(h); 
var svg = bdxf.dxf.toSVG(h)
console.log(svg); 
</script>
```

I'm sure there's got to be a more preferred way of doing it that you could recommend in your documentation.  

It would be a pretty useful capability to be able to parse/extract data or plot DXF files that have been downloaded natively in the browser without any server-side scripts.

**Comment by bjnortier** [comment]
Thanks. That should be clearer in the documentation or I will create a bundle in the distribution with an example of how to use

I use webpack for everything...

**Comment by bjnortier** [comment]
I've added a browserify example and a browser distribution in 3.0.3. I you think it's sufficient, please close the issue 👍
