### ISSUE TITLE
Weird svg output on 4 vertex polyline, all with radiuses

### ISSUE THREAD

**Issue by verner-lall** [bjnortier/dxf#21]
[output.zip](https://github.com/bjnortier/dxf/files/1775868/output.zip)

**Comment by verner-lall** [comment]
zip contains svg, dxf and dxf_preview.png

Should look like this:
![image](https://user-images.githubusercontent.com/9843535/36909586-0d3e900c-1e47-11e8-840a-8f9313e16351.png)

looks like this:

![image](https://user-images.githubusercontent.com/9843535/36909608-23009f0c-1e47-11e8-8565-4ff53674c34f.png)

**Comment by bjnortier** [comment]
Investigating...

**Comment by bjnortier** [comment]
Thanks for submitting this. The "bulge" property was not handled properly when the bulge occurred on the last vertex of a "closed" polyline entity. 

Fixed. 
Published as version 3.1.1

![screen shot 2018-03-05 at 11 25 43](https://user-images.githubusercontent.com/57994/36967283-f88fd030-2067-11e8-9a5c-5cb423b881b8.png)
