### ISSUE TITLE
Deformed and failing SVG

### ISSUE THREAD

**Issue by jellevr** [bjnortier/dxf#27]
Hello,

I'm using your library for which I want to thank you first, it has been a huge help. Most of the DXF work like a charm but some are deformed and some even fail so I figured I'll let you know, maybe you are unaware.

These are the DXF files that are deformed (downloadable through the link):

http://www.dewesp.com/v6/DXF/cardboard-cupcake-stand-easy-diy-craft-idea.dxf
http://www.dewesp.com/v6/DXF/laser-cut-ornaments-christmas-wood-tree-idea.dxf
http://www.dewesp.com/v6/DXF/plywood-candle-holder-laser-cutter-idea.dxf
http://www.dewesp.com/v6/DXF/rocking-elephant-cnc-router-plans-wood-rocking-horse-idea.dxf

Further I have some that completely fail:

http://www.dewesp.com/v6/DXF/chair.dxf
http://www.dewesp.com/v6/DXF/FV4EBZBGDVZF630.dxf
http://www.dewesp.com/v6/DXF/StaticBoot3-R14.dxf
http://www.dewesp.com/v6/DXF/Velociraptor.dxf

If I can be of any assistance, please let me know 👍 

Kind regards and again, big thank you for the library!

Jelle

**Comment by bjnortier** [comment]
Hi, thanks, I'll have a look. I always appreciate getting broken examples as the spec is quite complex so it's hard to anticipate all use cases.

**Comment by bjnortier** [comment]
Do you have images of what you expect the deformed one to look like?

**Comment by bjnortier** [comment]
Ok the first one was easier than I expected - these DXFs are splines with LOTS of control points, and previously the number of interpolated points was a constant. Now it is proportional to the number of control points:

![screen shot 2018-07-12 at 09 42 38](https://user-images.githubusercontent.com/57994/42619344-18325060-85b8-11e8-9685-b4d717e222c2.png)

I'll look at the ones that completely fail now...

**Comment by jellevr** [comment]
You are a saint! If I can buy you a coffee somehow, I'd me more than happy too. Thanks for the quick help!

**Comment by bjnortier** [comment]
The ones below are working now (there's a floating point issue in the b-spline lib, #28), which has to be addressed. I'll make a release now with these fixes - more work is needed for FV4EBZBGDVZF630.dxf and StaticBoot3-R14.dxf but at least you can get on with it.

![screen shot 2018-07-12 at 10 38 09](https://user-images.githubusercontent.com/57994/42622143-00cf4fd8-85c0-11e8-9e50-40e5c30146f7.png)
![screen shot 2018-07-12 at 10 39 07](https://user-images.githubusercontent.com/57994/42622145-010370a6-85c0-11e8-94d0-8183886b6ad5.png)

**Comment by jellevr** [comment]
Perfect, I really appreciate this!

I forgot one more that fails because it's on a different server:

https://discuss-assets.s3.amazonaws.com/original/3X/f/7/f754fb4dfe8ea2be046c2a23cf8f3e7ed8f5e8c9.dxf

Cheers,

Jelle

**Comment by bjnortier** [comment]
Published @3.2.1

**Comment by bjnortier** [comment]
Can I add these files to the test examples in the repo? Or are they copyrighted?

**Comment by jellevr** [comment]
you can, besides chair.dxf because I'm not sure about that one, all the others I got from a forum for testing myself :)

**Comment by bjnortier** [comment]
👍 

Chair is a bit bit anyways - I'll just extract the one curve that generates the error

**Comment by jellevr** [comment]
Hi Ben,

I adjusted my own code and retested everything. A huge improvement!

I am however still having problems with these:

http://www.dewesp.com/v6/DXF/plywood-candle-holder-laser-cutter-idea.dxf

![image](https://user-images.githubusercontent.com/38509352/42631927-e5dae82e-85db-11e8-8973-c70e9822211c.png)

The right top figure isn't correct, all the others are.

http://www.dewesp.com/v6/DXF/Velociraptor.dxf

It works if I open it from "\dxf\examples\dxf.html" in a browser and show the svg. But it doesn't when I call it from my app. Maybe it's my side but I don't think so as I'm calling the routine as I do with every DXF.

Again thank you, it's already a huge improvement.

**Comment by bjnortier** [comment]
Not sure why the top right one is problematic - it has a similar number of knots & control points to the others. I will have a look in the next couple of days.

**Comment by bjnortier** [comment]
Ok the spline interpolation is much smarter now, so the candle holder is fixed:

![screen shot 2018-07-13 at 16 55 31](https://user-images.githubusercontent.com/57994/42698233-95a36d76-86bd-11e8-8371-8f2ab91a731b.png)

You'll also see that the dxf.html example web page will render the SVG so it's easier to test any DXF

**Comment by jellevr** [comment]
I already implemtent that feature myself but it beats having to copy it every time :) thanks again Ben!

**Comment by bjnortier** [comment]
Do you want to close the issue?

**Comment by jellevr** [comment]
Yes, I think everything is addressed at this point :) thanks again!!!
