### ISSUE TITLE
b-spline lib fails on floating point error

### ISSUE THREAD

**Issue by bjnortier** [bjnortier/dxf#28]
The b-spline lib domain check can fail due to a floating point error - either the lib must be updated or the error caught and handled.

**Comment by bjnortier** [comment]
Pull request submitted to b-spline: https://github.com/thibauts/b-spline/pull/13

**Comment by davidgilbertson** [comment]
Ah I just logged a bug with `b-spline` before finding this: https://github.com/thibauts/b-spline/issues/14

It looks like `b-spline` is dead, would you consider forking it or removing the dependency? This bug is blocking us from importing some DXFs.

Is that a lot of effort?

**Comment by bjnortier** [comment]
Thanks!

I'll do a bit of maintenance today and will probably just incorporate the algorithm into dxf since this library is inactive

**Comment by bjnortier** [comment]
Published 3.4.0 which incorporates b-spline into the lib and removes the b-spline dependency
