### ISSUE TITLE
Pulling information regarding Layers.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [bjnortier/dxf#3]
From what I can tell the code 8 is for Layer String.

See the following: 
http://www.autodesk.com/techpubs/autocad/acadr14/dxf/common_group_codes_for_symbol_table_entries_al_u05_c.htm
https://github.com/thomasdesmoulin/dxf-parsing/blob/master/libs/parser.js#l=70-71
https://github.com/duckinator/dxf2svg/blob/master/entities.cpp

I will possibly code this in for all entities.
I would also like to pull the layers and group objects by layer.

I have branched and can look at doing this.

**Comment by bjnortier** [comment]
Awesome

**Comment by Allov** [comment]
Did we lose this functionality in version 2 ? I can't seem to get groups in the parsed object.

**Comment by LiamKarlMitchell** [comment]
Yeah I think we did, I looked at updating to newer version but it broke the functionality which we use this library for in some software we (my work) maintain, so I didn't bother to investigate updating further as I had a lack of time for investigating it.

**Comment by bjnortier** [comment]
1. @LiamKarlMitchell v2 isn't backward compatible with < 2, the structure has changed, so some work is needed to upgrade, but there is a lot more functionality like layer styles so it's worth the effort.
1. @Allov The functionality has not been lost, it's actually been improved, e.g. nested blocks are now supported. It's easy to group the entities, I'll add this as a convenience function:

```
'use strict';

const fs = require('fs');
const keys = require('lodash.keys');

const dxf = require('..');
const parsed = dxf.parseString(fs.readFileSync(
  '../test/resources/Ceco.NET-Architecture-Tm-53.dxf', 'utf-8'));

// Denormalise the entities out of the parsed structure - block transforms
// are added to the entities in this step
const entities = dxf.denormalise(parsed);

const groups = entities.reduce((acc, entity) => {
  const layer = entity.layer;
  if (!acc[layer]) {
    acc[layer] = [];
  }
  acc[layer].push(entity);
  return acc;
}, {});

console.log('[layer : number of entities]');
keys(groups).forEach(layer => {
  console.log(layer, ':', groups[layer].length);
});
```

**Comment by bjnortier** [comment]
I pushed a new version with groupEntitiesByLayer , added some examples in examples/, and updated the README:

```
'use strict';

const fs = require('fs');
const keys = require('lodash.keys');

const dxf = require('..');
const parsed = dxf.parseString(fs.readFileSync(
  '../test/resources/Ceco.NET-Architecture-Tm-53.dxf', 'utf-8'));

// Denormalise the entities out of the parsed structure - block transforms
// are added to the entities in this step
const entities = dxf.denormalise(parsed);

// Group entities by layer. Returns an object with layer names as
// keys to arrays of entities
const groups = dxf.groupEntitiesByLayer(entities);

// Ouptut the groups
console.log('[layer : number of entities]');
keys(groups).forEach(layer => {
  console.log(layer, ':', groups[layer].length);
});
```
