### ISSUE TITLE
OpenSCAD exported dxf file fails

### ISSUE THREAD

**Issue by hungerpirat** [bjnortier/dxf#34]
In the attached file no tables are defined, if I understand dxf right (I am new to dxf).

Therefore the library fails at https://github.com/bjnortier/dxf/blob/master/src/toSVG.js#L49
I was able to "fix" this behaviour by adding one line here: https://github.com/bjnortier/dxf/blob/master/src/index.js#L98
```tables: {layers: {}, styles: {}}```
Though it works for me I am in doubt if that is a proper fix. I don't understand the dxf format well enough to decide where to fix it. I hope this is helpful in any way. Feel free to give me a hint where to fix it properly, then I will provide a pull request.

[openscad_export.zip](https://github.com/bjnortier/dxf/files/2343550/openscad_export.zip)

p.s. keep up the good work! Thanks.

**Comment by bjnortier** [comment]
Published in 3.3.0

**Comment by bjnortier** [comment]
Please close the issue if you're happy

**Comment by hungerpirat** [comment]
Thanks!
