### ISSUE TITLE
Use native <circle> elements for circles

### ISSUE THREAD

**Issue by bjnortier** [bjnortier/dxf#35]

**Comment by ceremcem** [comment]
Any schedule available?

**Comment by bjnortier** [comment]
@ceremcem Deployed in 4.1.0

the library now uses <cirlcle />, <ellipse /> and <path d="A..." /> (native arcs) for SVG export.

SPLINEs coming soon

**Comment by ceremcem** [comment]
Great! I'll try to switch back to this library from my own hack as soon as possible.
