### ISSUE TITLE
is there any way to parse a json string  into a dxf file?

### ISSUE THREAD

**Issue by Mrluobo** [bjnortier/dxf#41]
I am working to build some graph and i want to make it become a dexf file let other people can open it in autoCAD.is there any way to parse a json string  into a dxf file?

**Comment by bjnortier** [comment]
Hi. This library only imports DXF, it can't generate DXF, unfortunately. I'm not aware of any libraries that can do that easily, but a quick Google shows up some C++ libraries for DXF export

**Comment by Mrluobo** [comment]
thank you very much, i found a library may could do this.  [jscad/io](https://github.com/jscad/io)

i hope it can work

**Comment by bjnortier** [comment]
Ooh interesting. I learned something. Thanks!
