### ISSUE TITLE
Some offset for ARC and circles

### ISSUE THREAD

**Issue by GDXFR** [bjnortier/dxf#42]
First of all, thank you for the great job!

I'm experimenting some troubles while converting models somes elements such as ARC and CIRCLES are shifted to x axis.

[test.zip](https://github.com/bjnortier/dxf/files/3318498/test.zip)

**Comment by bjnortier** [comment]
I've been looking at it now - the bug is that when a horizontal flip is specified on the entity itself (as opposed to the transform), it is not applied.

Working on a fix...

**Comment by bjnortier** [comment]
I have a fix, just waiting for Travis to release.

Before:

![Screenshot 2019-06-24 at 11 56 41](https://user-images.githubusercontent.com/57994/60010040-3ff7f480-9677-11e9-98b6-03f4ec2f016f.png)

After:

![Screenshot 2019-06-24 at 11 54 48](https://user-images.githubusercontent.com/57994/60010048-44bca880-9677-11e9-8dfe-e684f9f60d9e.png)

**Comment by bjnortier** [comment]
Fix released in 4.1.1

**Comment by GDXFR** [comment]
Whoo, great thank guys.

Regards,
Gwenael Delaleux
