### ISSUE TITLE
Can't Draw Hatch's and Patterns

### ISSUE THREAD

**Issue by Monarkos** [bjnortier/dxf#43]
Hi there,

I'm using the lib to draw on some section based on dxf file, but for no reason the Hatch Pattern is ignored during de conversion to polylines, then those parts are aways missing.
Could anyone help me?

Thank you

**Comment by bjnortier** [comment]
Hi, HATCH is not supported for SVG rendering, if you read the README there’s a list of unsupported entities for SVG.

HATCH was part of “and others” but I’ve now made it more clear in the README.

**Comment by Monarkos** [comment]
Thank you for the quick answer @bjnortier.
There's plan for be implemented on the future?

**Comment by bjnortier** [comment]
Nope no plan. Hatches were not required for what I wrote the library for, and I don’t foresee needing them. I’m happy to implement them for a fee like I’ve done for other users of the library.

**Comment by bjnortier** [comment]
Or accept pull requests of course
