### ISSUE TITLE
Sample Files

### ISSUE THREAD

**Issue by z3dev** [bjnortier/dxf#44]
First, I just wanted to say thanks for creating a really nice set of sample files. I've been looking for small samples for a long long time.

If you are also interested, there is a set of sample files found at JSCAD; https://github.com/jscad/sample-files

Our focus is more on 3D designs but many designs start from 2D shapes, etc.

![1](https://user-images.githubusercontent.com/8969165/63489544-61495580-c4ed-11e9-8b45-1ac710a880be.png)

I'll be back to take a look at the spline implementation, as we need to add that to our parser in the future.

Thanks much!

**Comment by bjnortier** [comment]
Thanks! I'm glad you're getting some value form this library.

I'll have a look at those other samples

**Comment by z3dev** [comment]
Cool! I hope those help in creating a really strong library.

Question... where did you get the list of colors?

I searched for lists and decided on some ‘standards’. But your list of colors is different.

**Comment by bjnortier** [comment]
http://gohtx.com/acadcolors.php

Except during SVG transform I convert white to black because the background is white
