### ISSUE TITLE
Autocad Color Indexes

### ISSUE THREAD

**Issue by z3dev** [bjnortier/dxf#45]
I've been searching around the internet again for a definitive color index. Once again, there are lots of lists, which don't match.

However, I ran into a discussion on the Autocad support blogs. And there was a very nice gentlemen that created color indexes for Autocad 2018 and Autocad 2017. I attached the spread sheet for your use.

[colorcomp.xlsx](https://github.com/bjnortier/dxf/files/3539470/colorcomp.xlsx)

I suspect that the color index changes whenever Autocad wants. Which is why DXF is such a huge mess.

If you have someone that has Autocad installed, they could verify the color index fairly quickly.

**Comment by bjnortier** [comment]
Thanks, like I said, I use http://gohtx.com/acadcolors.php, and it's close enough to the spreadsheet you sent.

 I agree DXF is a huge mess.
