### ISSUE TITLE
toSVG gives incorrect bounding box for arcs

### ISSUE THREAD

**Issue by ericman314** [bjnortier/dxf#47]
Thanks for this awesome library! It's super accurate and fast.

I'm using the library to convert some DXFs to SVGs for rendering in a browser. Some of the DXFs have arcs that are very nearly flat. The arcs themselves are small but the bounding box calculated in `toSVG` is too large. It looks like it contains the entire circle the arc came from. I would expect that the bounding box only contain the arc itself.

I set up a repo demonstrating this: https://github.com/ericman314/test-arc-bbox

Using Inkscape to open the generated SVG, you can see that the document size (viewBox) is much larger than the actual arc:

![image](https://user-images.githubusercontent.com/6345617/67453928-89386080-f5e5-11e9-954b-4e00e882d9ff.png)

As for a possible cause, I think this might be the culprit: https://github.com/bjnortier/dxf/blob/a732803e065479747f1ac706781860c942d97c4b/src/toSVG.js#L65-L78

I think what this does is it takes the corners of the rectangle containing the ellipse, and rotates them by `rotationAngle`. A more accurate bounding box would only include the endpoints of the rotated arc, as well as any points on the rotated arc that have a vertical or horizontal tangent line. Definitely more tricky, but it would be a true bounding box for the arc.

**Comment by bjnortier** [comment]
Indeed.

As you say the bounding box is the rectangle of the full circle, which as you say works well enough for larger arcs but is a problem for shorter ones. This is a pragmatic solution but not ideal. It shouldn't be too difficult to do it properly, just need to consider all the different combinations. 

A feasible algorithm might be:
1. Calculate first point & add to bounding box.
2. Calculate end point & add to bounding box. 
3. For each extremity in the arc add those to the bbox (i.e. 90deg, 180deg, etc., if they are within the start and end point).

**Comment by bjnortier** [comment]
I'm happy to do this if you can supply a couple of DXFs as test cases, which will save me some time. A combination of elliptical and circular arcs with different combinations of start & end angles would be good.

**Comment by ericman314** [comment]
Thanks for the quick response! I added some DXFs to the repo: https://github.com/ericman314/test-arc-bbox/tree/master/dxfs

How will you calculate the extremities? I'm not sure they will be located at multiples of 90 deg. 

UPDATE: After spending a little while on this, I worked out the locations of the extremities. I started with the function below that returns points and tangent lines of an ellipse. Then I solved for the angles that give the tangent vector a zero x component or y component. My work is below; sorry for the poor quality and bad handwriting!

```js
/**
 * Interpolate an ellipse
 * @param angle Angle at which to return the interpolated point
 * @param x center X
 * @param y center Y
 * @param majorX major axis X
 * @param majorY major axis Y
 * @param axisRatio major/minor axis ratio
 * @returns {Object} The interpolated point and tangent vector.
 */
function pointOnEllipse(angle, x, y, majorX, majorY, axisRatio) {

  // Start with a unit circle, then multiply by the transformation matrix which is formed by the major axis, and a vector perpendicular to that and scaled by axisRatio

  // Transformation matrix, formed by the major and minor axes
  let M =
    [[majorX, -majorY * axisRatio],
    [majorY, majorX * axisRatio]]

  // Point on the unit circle
  let u = {
    x: Math.cos(angle),
    y: Math.sin(angle)
  }

  // Tangent to the unit circle
  let t = {
    x: -u.y,
    y: u.x
  }

  // Rotated and scaled point
  let v = {
    x: u.x * M[0][0] + u.y * M[0][1] + x,
    y: u.x * M[1][0] + u.y * M[1][1] + y
  }

  // Rotated and scaled tangent
  let w = {
    x: t.x * M[0][0] + t.y * M[0][1],
    y: t.x * M[1][0] + t.y * M[1][1]
  }

  return { point: v, tangent: w }
}
```
![IMG_20191024_071145](https://user-images.githubusercontent.com/6345617/67489254-8150de80-f62e-11e9-8416-6fc6e06a9481.jpg)

**Comment by bjnortier** [comment]
You're right, I meant that in the *unrotated* case the extremities will be located on the 0,90,180,270 deg points, depending on which of those are between the start and end angle:

![IMG_5687](https://user-images.githubusercontent.com/57994/67569108-3d450300-f72e-11e9-829d-db1aa5071037.jpg)

The resulting box will be a big too big when rotated. Call this method B (where A is the current implementation)

If you want to use the interpolated approach, you can just calculate each point on the interpolated ellipse and add that to the bounding box, without really worrying about tangents. This does imply a performance hit for arcs and a DXF with many arcs will suffer.

P.S. Thanks for the DXFs.
P.P.S. If you feel like you'd like to submit a pull request for this I'd be happy to accept that.

**Comment by bjnortier** [comment]
Publish as 4.2.3 - if that works for you you can close this issue 👍

**Comment by ericman314** [comment]
Thanks!
