### ISSUE TITLE
__defineGetter__ is deprecrated in favour of defineProperty

### ISSUE THREAD

**Issue by LiamKarlMitchell** [bjnortier/dxf#5]
It seems like it may not be a good idea to use `__defineGetter__`

What are your thoughts?

See the following:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

**Comment by bjnortier** [comment]
Ah interesting. Yes if this is the new standard __defineGetter__ should not be used any longer, if the new standard is supported in Chrome/Safari/Firefox
