### ISSUE TITLE
toSVG gives NaN viewBox if DXF has polygonMesh or polygonFace

### ISSUE THREAD

**Issue by ericman314** [bjnortier/dxf#51]
Sometimes, the viewBox in an SVG is all NaNs. This one was a tough nut to crack, but I think the sequence of events goes like this:

1. A DXF file is parsed, which contains a POLYLINE or LWPOLYLINE entity with the `polygonMesh` or `polygonFace` property set
1. Call `helper.toSVG`
1. In `entityToPolyline.js`, polygonMeshes and polygonFaces are not rendered, so `vertices` is an empty array
1. Because `vertices` is empty, the bounding box is `{ min: { x: Infinity, y: Infinity }, max: { x: -Infinity, y: -Infinity } }` So far so good.
1. In `transformBoundingBoxAndElement`, the bounding box is transformed, and somewhere in there it does `Infinity - Infinity` which becomes `NaN`
1. The SVG gets `NaN`s for its viewBox

I'm not sure where the appropriate place would be to interrupt this chain of events. Possibly, skip transforming a bounding box if it is infinite? Or skip output of a path entirely if it contains no vertices? I'm happy to submit a PR if you can give some direction.

**Comment by bjnortier** [comment]
Thanks for the debugging! Will fix it now. Transforming the bounding box makes no sense so I think I'll add it there, but also add a new method on the bounding box to check for "empty" or something like that instead of checking for Infinity

**Comment by bjnortier** [comment]
Do you have a DXF for this I can add to the test suite?

**Comment by bjnortier** [comment]
I believe it's fixed in 4.3.0 - let me know

**Comment by ericman314** [comment]
Now instead of giving a NaN viewBox, it's giving an infinite viewBox. What if there was a check here to only extend a bounding box if it is valid?

https://github.com/bjnortier/dxf/blob/a17d453d156a42d1a2a10a17d4e2f5e0f35afad5/src/toSVG.js#L267-L272

Something like:

```js
if (boundsAndElement) { 
   const { bbox, element } = boundsAndElement 
   if (bbox.valid) {
     acc.bbox.expandByPoint(bbox.min) 
     acc.bbox.expandByPoint(bbox.max) 
   }
   acc.elements.push(`<g stroke="${rgbToColorAttribute(rgb)}">${element}</g>`) 
 } 
```

Sorry for all the trouble, these are parts that people submit online and the quality of the drawings can vary wildly. Sometimes I can't reproduce all the issues in one of my own files as the DXF format is a bit mysterious to me.

**Comment by bjnortier** [comment]
Send me the example DXF...

**Comment by bjnortier** [comment]
But yes that should work

**Comment by bjnortier** [comment]
Try 4.3.1

**Comment by ericman314** [comment]
It works! Thank you.
