### ISSUE TITLE
circles are placed wrong after converting to svg

### ISSUE THREAD

**Issue by hungerpirat** [bjnortier/dxf#52]
I converted the attached dxf file using the cli dxf-to-svg. While all path elements in the resulting svg are placed fine, the circle elements have wrong coordinates (very far away). Find the conversion result in the .zip as well.

[dxf_with_problems.zip](https://github.com/bjnortier/dxf/files/3881293/dxf_with_problems.zip)

Thanks in advance for all your efforts.

**Comment by bjnortier** [comment]
Hi, I have a fix.

There was a bug in the transformation matrix application when inserting blocks.

I'll create a new release now.

P.S. Sorry for the delay, I don't use this for commercial work anymore so it's just my free time.

**Comment by bjnortier** [comment]
![Screenshot 2019-12-10 at 15 27 56](https://user-images.githubusercontent.com/57994/70535189-3f8be100-1b65-11ea-9cf7-b08b9c3f37ee.png)

**Comment by bjnortier** [comment]
Published in 4.3.3

**Comment by hungerpirat** [comment]
Many thanks Ben @bjnortier. I highly appreciate your efforts. In any case, this is one of the most well maintained pieces of code out there.

**Comment by bjnortier** [comment]
Thanks :)

**Comment by bjnortier** [comment]
Please close the issue if it fixes it for you

**Comment by hungerpirat** [comment]
Many Thanks for your efforts! Awesome project btw. In my whole working life I've not seen many projects as well maintained and documented as this one. Great piece of work!

**Comment by bjnortier** [comment]
Thank you :)
