### ISSUE TITLE
bSpline interpolation can produce parameter t outside range [0,1]

### ISSUE THREAD

**Issue by calebc01** [bjnortier/dxf#53]
In entityToPolyline.js, the following code is used to produce the parameter t to generate points along the polyline:

`var t = (u - domain[0]) / (domain[1] - domain[0]);`

I'm not sure what causes the problem, but some splines produce a t value just outside the allowed range of [0,1]:

>  Error: t out of bounds [0,1]: 1.0000000000000002
>     at _default (C:\_oshcut\Software\cadproc\node_modules\dxf\lib\util\bSpline.js:22:11)
>     at interpolateBSpline (C:\_oshcut\Software\cadproc\node_modules\dxf\lib\entityToPolyline.js:101:39)

Could be a numerical precision issue.  The following fixes the problem:

`var t = Math.min(1, Math.max(0, (u - domain[0]) / (domain[1] - domain[0])));`

It might be a band-aid fix, but it does the job.  I can send you the file that causes the issue if you want to see it.

**Comment by bjnortier** [comment]
Ah ok. Will fix now. There's a similar clamping feature inside the bSpline.js code itself, but I can see how it can be an issue.

**Comment by bjnortier** [comment]
Please send the file so I can test it. Can I add it to the repo as a test case or is it a private file?

**Comment by bjnortier** [comment]
Fix released in 4.3.4

**Comment by calebc01** [comment]
The fix works, thanks!
[BA-SPR-M1-13 - cleaned.zip](https://github.com/bjnortier/dxf/files/4036999/BA-SPR-M1-13.-.cleaned.zip)  File for test attached, if you still want it.

**Comment by bjnortier** [comment]
Ok awesome. Will add it to the test suite
