### ISSUE TITLE
3DFace support

### ISSUE THREAD

**Issue by Xander-Tyker** [bjnortier/dxf#54]
Hi,

Is it possible to add support for 3Dfaces?

Kind regards,
Xander

**Comment by bjnortier** [comment]
Do you have an example DXF that contains 3D faces? Not sure how hard they are to parse. And SVG rendering for 3D faces will not be applicable.

**Comment by z3dev** [comment]
@bjnortier please see JSCAD sample files. You’ll find some examples of 3D models.

**Comment by bjnortier** [comment]
Added support and released in 4.3.5. The corners will be parsed into the "vertices" array in the entity.

Note that 3DFACE is not supported in SVG rendering.

**Comment by Xander-Tyker** [comment]
Works perfectly.
Thank you very much!
