### ISSUE TITLE
Drawing Unit 

### ISSUE THREAD

**Issue by evamueller** [bjnortier/dxf#55]
The unit of the DXF measurements is given under the heading "$INSUNITS". I would like to be able to read this out and additionally scale the DXF to another dimension.

**Comment by bjnortier** [comment]
I've added 'insUnits' and 'measurement' to the parsed header in version 4.3.6

**Comment by evamueller** [comment]
man, thank you, that was fast!

**Comment by bjnortier** [comment]
Pleasure, you can close this issue if this does what you require :)
