### ISSUE TITLE
DXF file can NOT be parser

### ISSUE THREAD

**Issue by Laioyu** [bjnortier/dxf#57]
I use webpack build my project and I am very sure the dIxf module has been load success when the project running. I try to find the point by debug with chrome but  when i  step into the dxf-lib function I was total puzzled by the source code. I upload two dxf file, they are only contain simply 2d entity, test2.dxf could be read normally and test1.dxf could‘t . It's worth noting that test2.dxf only contain lowpolyline entities but test1.dxf not.

There is my code 
typesript：
```

import * as THREE from "three";
import { ExtrudeGeometryOptions, Color, Curve, Vector2 } from "three";
import { TrackballControls } from 'three/examples/jsm/controls/TrackballControls';
import DxfParser from "dxf-parser";
import dxf = require("dxf");

var numberOfEntities = document.getElementById('numberOfEntities')
var svgContainer = document.getElementById('svg')
var fileInput = document.getElementById('file')

interface HTMLInputEvent extends Event {
    target: HTMLInputElement & EventTarget;
}

function OnSelectFile(event: HTMLInputEvent): void {
    var file = event.target.files[0];
    var reader = new FileReader();
    numberOfEntities.innerHTML = 'reading...'
    reader.onload = function (e) {
        if (e.target.readyState === 2) {
            var dxfContents = e.target.result;
            var dxfHelper = new dxf.Helper(dxfContents);
            numberOfEntities.innerHTML = dxfHelper.denormalised.length;
            const parsed = dxfHelper.parsed;
            const svg = dxfHelper.toSVG();
            const lines = dxfHelper.toPolylines();
            svgContainer.innerHTML = svg;
        }
    }
    reader.readAsBinaryString(file)
}

fileInput.addEventListener('change', OnSelectFile);

let camera, scene: THREE.Scene, renderer, controls: TrackballControls;



function init() {
    renderer = new THREE.WebGLRenderer();
    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(window.innerWidth, window.innerHeight);
    document.body.appendChild(renderer.domElement);

    scene = new THREE.Scene();
    scene.background = new THREE.Color(0xb0b0b0);

    camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 1, 1000);
    camera.position.set(0, 0, 500);

    controls = new TrackballControls(camera, renderer.domElement);
    controls.minDistance = 200;
    controls.maxDistance = 500;

    scene.add(new THREE.AmbientLight(0xcccccc));

    var directionalLight = new THREE.DirectionalLight(0xffffff, 0.6);
    directionalLight.position.set(0.75, 0.75, 1.0).normalize();
    scene.add(directionalLight);

    var group = new THREE.Group();
    scene.add(group);

    var helper = new THREE.GridHelper(160, 10);
    helper.rotation.x = Math.PI / 2;
    group.add(helper);

    let axis = new THREE.AxesHelper(1000)
    scene.add(axis);

    let closedSpline = new THREE.CatmullRomCurve3([
        new THREE.Vector3(0, 0, 0),
        new THREE.Vector3(0, 0, 100),

    ]);


    let pts = new Array<THREE.Vector2>();

    pts.push(new Vector2(0, 0));
    pts.push(new Vector2(10, 0));
    pts.push(new Vector2(10, 10));
    pts.push(new Vector2(0, 10));

    // for (let i = 0; i < 4; ++i) {
    //     var l = 20;
    //     var a = 2 * i / 4 * Math.PI;
    //     pts.push(new THREE.Vector2(Math.cos(a) * l, Math.sin(a) * l));
    // }
    let shape = new THREE.Shape(pts);

    let extrudeOptions: ExtrudeGeometryOptions = { steps: 100, bevelEnabled: false, extrudePath: closedSpline };
    let geometry = new THREE.ExtrudeGeometry(shape, extrudeOptions)

    let material = new THREE.MeshLambertMaterial({ color: 0xE9DC04, wireframe: false });
    let mesh = new THREE.Mesh(geometry, material);
    scene.add(mesh);
}

init();

function animate() {
    requestAnimationFrame(animate);
    controls.update();
    renderer.render(scene, camera);
}
animate();

```
html part ：
```
<!DOCTYPE html>
<html>

<head>
  <title>threejs-learn</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>
    .box {
      border: 1px;
      width: 300px;
      height: 300px;
    }
  </style>
</head>

<body>
  <input type="file" id="file" />
  <div>Number of entities:<span id="numberOfEntities">-</span></div>
  <div id="svg" class="box"></div>
  <script type="text/javascript" src="./dist/main.js"></script>
</body>

</html>
```

Debug with chrome and test1.dxf  can not be read and show
![image](https://user-images.githubusercontent.com/33061113/79636693-21d22680-81ac-11ea-9721-7d3aad79dafb.png)

Debug with chrome and test2.dxf can be read and show well
![image](https://user-images.githubusercontent.com/33061113/79693215-ef9ff200-829b-11ea-9959-a6d6c8350ebb.png)

dxf files I want to be parse 
[dxf-text.zip](https://github.com/bjnortier/dxf/files/4496529/dxf-text.zip)

**Comment by z3dev** [comment]
The HTML and JavaScript seem slightly wrong. You need to update an SVG element or CANVAS element with the contents. Here’s a tutorial on SVG rendering.

https://www.w3schools.com/html/html5_svg.asp

I’m sure others have done this.

**Comment by Laioyu** [comment]
> The HTML and JavaScript seem slightly wrong. You need to update an SVG element or CANVAS element with the contents. Here’s a tutorial on SVG rendering.
> 
> https://www.w3schools.com/html/html5_svg.asp
> 
> I’m sure others have done this.

I have updated description of the question and I paste all my code. two dxf file for test also has been upload.  I am newer in front-end development so I need help indeed. I am very sure I have rendered the canvas, test2.dxf  have been drawed success is evidence, but test1.dxf file cant not be
draw at all, even without any message in log. I read the diffrence between two dxf file.  the test2.dxf
file only contains lowpolyline entites .  I doubt test1.dxf has contains other element to represent 2d graphic which can be read normly in AutoCad but out of this lib's work!

**Comment by bjnortier** [comment]
test1.dxf doesn't contain any standard geometry entities, which is why it renders empty.

It does contain a "REGION" section, which I *think* is an ACIS region, but this is completely undocumented in the DXF spec and not supported in this library:

![Screenshot 2020-04-20 at 12 31 04](https://user-images.githubusercontent.com/57994/79742272-d8e0b600-8302-11ea-97c8-93664dcab8f5.png)

**Comment by Laioyu** [comment]
> test1.dxf doesn't contain any standard geometry entities, which is why it renders empty.
> 
> It does contain a "REGION" section, which I _think_ is an ACIS region, but this is completely undocumented in the DXF spec and not supported in this library:
> 
> ![Screenshot 2020-04-20 at 12 31 04](https://user-images.githubusercontent.com/57994/79742272-d8e0b600-8302-11ea-97c8-93664dcab8f5.png)

Thank you very much for your help. it is the final answer to my qustion！

**Comment by bjnortier** [comment]
Pleasure 👍🏼
