### ISSUE TITLE
How to parse arrayed features?

### ISSUE THREAD

**Issue by ericman314** [bjnortier/dxf#58]
I have a part that has an array of circles, but only the first circle is being parsed. I'm using `helper.denormalised` to access the parsed entities.

The part should look like this:
![image](https://user-images.githubusercontent.com/6345617/80004228-503b5480-847f-11ea-94c8-cdfda81df3c6.png)

Instead, it is being rendered like this (using `helper.toSVG()`):
![image](https://user-images.githubusercontent.com/6345617/80004469-985a7700-847f-11ea-9732-e6b24fbc7901.png)

Here is the DXF of the part:

[arrayed-holes (1).zip](https://github.com/bjnortier/dxf/files/4517463/arrayed-holes.1.zip)

Is is possible to support arrayed features? The library has been a wonderful tool for me and I'd like to contribute if I can, but I'm not sure where to start.

**Comment by ericman314** [comment]
Updated previous comment with a new version of the DXF. The old version had a bunch of extra blocks and layers in it. New version: [arrayed-holes (1).zip](https://github.com/bjnortier/dxf/files/4517463/arrayed-holes.1.zip)

**Comment by ericman314** [comment]
My understanding of the DXF format is basically non-existent, but I was able to identify this location in the file that seems to specify the feature array:

```
AcDbBlockReference
  2
1-4_HOLE
 10
-1.477361970195621
 20
6.875000000000004
 30
0
 41
1
 42
1
 43
0
 50
0
 70
    1
 71
   14
 44
0
 45
-0.5
```

Parameter 71 appears to be the repeat count, and 44 and 45 is the offset vector for each repetition. If I am not mistaken, this is a block reference that places entities defined in that block onto the drawing. I'm sure you understand better how this works in the full context of the DXF, and hopefully it is a simple matter to use parameters 71, 44, and 45 to replicate the block multiple times.

**Comment by ericman314** [comment]
After more digging, I discovered that these parameters _are_ being parsed correctly. However, the repetition is not taken into account in `denormalise.js`. In that file, I can see that an INSERT entity's entities are recursively added. I will try wrapping the appropriate sections in that file in a loop to add repeated entities.

**Comment by z3dev** [comment]
INSERT... cool. A new DXF entity type. Thanks for the example.
