### ISSUE TITLE
Would you like have toSVG and toSVGPath methods?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [bjnortier/dxf#6]
I had to code something to do this for work in the interest of contributing back to open source project, I can provide a pull request for it if you like.

Not every feature of DXF works but hey its a start :).

![image](https://cloud.githubusercontent.com/assets/1968109/7311270/30626148-ea8e-11e4-9a11-36722f25b9c4.png)

![image](https://cloud.githubusercontent.com/assets/1968109/7311256/08d8f556-ea8e-11e4-9bb6-857d9d1fba11.png)

**Comment by bjnortier** [comment]
Having SVG functions would be amazing.  

If you can supply the functions I can add some functional tests for those in the form of static HTML
