### ISSUE TITLE
question about a filling problem

### ISSUE THREAD

**Issue by nattyluke** [bjnortier/dxf#73]
Hello, first of all thank you for your wonderful parser.
I'm trying to load an DXF file into an svg (which just contains a circle), which works nice after some adjustments:
![image](https://user-images.githubusercontent.com/23554225/118961128-4460e100-b964-11eb-978c-5603bdb20c78.png)

Im using the toPolylines() method and iterate over all polylines. 
My Problem is filling the inner of the Path. If i group all lines in a g-tag and do fill="white" it looks like that:
![image](https://user-images.githubusercontent.com/23554225/118961568-be916580-b964-11eb-94fa-d74531de740a.png)
When I put all polyline in a single Path/Polyline (and fill white)  i get:
![image](https://user-images.githubusercontent.com/23554225/118961790-01533d80-b965-11eb-8651-765a0b98d8bb.png)

Do you have any ideas to fill the inner?
Thank you for your help.

**Comment by bjnortier** [comment]
For SVG you would have to make a single path from the polylines, but the order is important. So I think for your single path they are not in the correct order?

I think you would have to write an algorithm that starts with one polyline, then matches the last point of that polyline to the first point of the correct polyline, and repeat until it's complete.

**Comment by nattyluke** [comment]
Aaah the polylines are not in the right order - that explains everything. Thank you for the tip. After reordering it looks quite good:
![image](https://user-images.githubusercontent.com/23554225/119115218-3627c900-ba27-11eb-820a-b72051f64002.png)
Somehow it cut oout/extended the white parts from the second image - the 'arky' parts...Now it looks a bit edgy... Do you have an idea for that problem too?
Thank you

**Comment by bjnortier** [comment]
Looks like you algorithm removed some of the points? If you renmove the fill you should be able to check just the path

**Comment by nattyluke** [comment]
I got it working, my algorithm was not working right. The points are not matching exact, now i take the nearest point.
![image](https://user-images.githubusercontent.com/23554225/119986214-dcde0d80-bfc3-11eb-921f-4ed2fbf29420.png)

For interested my algorithm is:

>         const helper = new Helper(dxf)
>         let polylines = helper.toPolylines().polylines.map(pl => pl.vertices)
>         let firstpoly = polylines.splice(0,1) 
>         let output = firstpoly[0]
>         while (polylines.length > 0) {
>             let lastpoint = output[output.length-1]  
>             //   Sort polylines by distance of their first points to lastpoint 
>             polylines = polylines.sort( (a,b) => {
>                     const adistance = pointDistance(a[0],lastpoint)
>                     const bdistance = pointDistance(b[0],lastpoint)
>                     return adistance - bdistance
>                 })
>             output = output.concat(polylines[0])
>             polylines.shift()
>         }
>         return output.map(v => `${v[0]},${v[1]}` ).join(' ')    
where pointDistance is a function which calculates the distance between 2 points

**Comment by bjnortier** [comment]
Nice :)
