### ISSUE TITLE
Support for binary DXFs

### ISSUE THREAD

**Issue by ericman314** [bjnortier/dxf#79]
Is this something that would be desired? We are thinking about supporting binary DXFs in our application and thought that this existing parser would be the perfect place to implement it. If so, I will give it a try and submit a PR.

**Comment by bjnortier** [comment]
It’s something I’m aware of but have seen no desire and I’ve never seen a binary DXF in the wild. I suppose zipping a text DXF gives you the same smaller file with without having to contend with another format

**Comment by z3dev** [comment]
I ditto that of @bjnortier 

Although the binary definition exists, I have never seen a binary DXF file. And for exchanging designs, DXF ASCII files are always preferred.

Is there another application, besides AutoCad, capable of generating DXF binary files?

**Comment by ericman314** [comment]
Out of thousands of submitted DXFs, I've only seen a few binary DXFs. Could actually be the same user over and over who has the binary setting turned on. 

The binary format is smaller than ASCII but only by about 25%. Nowhere near the 80-90% compression you would get by zipping.

At the time it was introduced, the binary format was probably intended to speed up reading and writing, but honestly that's probably not much of a concern any more.

So I obviously agree with both of you that the binary format doesn't have many advantages over ASCII, but, users will be users.

I looked more closely at `parseString.js`. Based on how the parsing is done currently, I don't think it could be easily converted to reading a binary file. More likely, an entirely new `parseBinary.js` would have to be written. 

For now, I will just write a preprocessor that converts binary to ASCII, and then pass that output to this library. If you decide to support binary in the future, I'll be happy to submit a PR which includes my implementation of `parseBinary`.
