### ISSUE TITLE
Filter by layer

### ISSUE THREAD

**Issue by bjnortier** [bjnortier/dxf#8]

**Comment by LiamKarlMitchell** [comment]
Could this be similar to `gatherDisplayEntities` but returning a Collection instance?

I wonder if the transforms on inserts could be  supplied independent of the entity as to not need cloning.

What do you think about Layers inheriting from Collection?
With the primitives then being stored per layer.

```
var filteredCollection = collection.filterByLayer(['L0','L1']);
```

Or some kind of filtering & searching chain-able query functions.
```
.find(['L0'],'circle').having('r','between', [100, 300])
```
linq like? http://hugoware.net/Projects/jlinq


Or were you thinking of a white/black filter of layers when initially parsing the DXF?

**Comment by bjnortier** [comment]
There will be no filtering during the parsing stage, filtering can be applied to entities afterwards in client code. 
This lib will not have linq-like filtering or any other kind of higher-order filtering - that is up to the client to implement
