### ISSUE TITLE
Proposal: Added types within `DefinitelyTyped` for this package - needs review

### ISSUE THREAD

**Issue by PrestonII** [bjnortier/dxf#81]
Firstly - love this package, thanks for creating it!

I needed some Typescript support so I went ahead and created types for it within [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56748). It does need some review however and while I'm comfortable contributing I'm sure it'd be good for the contributors here to have eyes on it as well.

Best!

**Comment by PrestonII** [comment]
An update: the types have been merged over here in case anyone would like to use them: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56748

**Comment by OoDeLally** [comment]
Thank you so much <3

**Comment by z3dev** [comment]
Probably a single TS file would suffice, and be easier to maintain.
