### ISSUE TITLE
The referenced package "pretty-data" is packaged with vite, and it runs abnormally

### ISSUE THREAD

**Issue by daydayuphuan** [bjnortier/dxf#85]
My project is built with vite, I used dxf, and the following error was reported when it was running.

![image](https://user-images.githubusercontent.com/7309887/146500966-efa2ab84-a813-4951-8860-098f9363c3a5.png)

dxf version: `4.6.1`
node version: `v14.18.1`
npm version: `6.14.15`

**Comment by bjnortier** [comment]
This is an issue with pretty-data then, not dxf

**Comment by eXaminator** [comment]
I stumbled across the same problem while trying to use this library.

@bjnortier While you are right that this is a bug in pretty-data, it doesn't seem that it is in any kind of active development. Maybe it would make sense to drop it and find some replacement?

**Comment by bjnortier** [comment]
Tagging @skymakerolof, he has taken over maintenance of the library :)
