### ISSUE TITLE
Exposing interpolate's internal methods + changes to toSVG

### ISSUE THREAD

**Issue by LiamKarlMitchell** [bjnortier/dxf#9]
Whilst I can appreciate the main goal is to parse DXF.
I am currently using it to implement a render to SVG and SVG Path. (with much older verison of the library)

The interpolate.js is nice if only working with lines with a fixed size.
However may I suggest to have the methods inside it exported also, so that they can be reused in other rendering code that may be added in as modules.

Some things that render modules might need to do:

- Text output, alignment, size, color rotation.
- Dimension Lines, measuring lengths and angles.
- Line caps, start and end arrows.
- Line styling, color, dashes, thickness.

Re-using some of the interpolate code would be helpful as then we can get the points to use whilst having access to other details on the DXF entities that would change the rendered appearance.

Interpolated points don't have a way to link to the entity they are for obviously.

**Comment by bjnortier** [comment]
If you're saying that after interpolation the relationship between entities and rasterised curves should be maintained, then I agree

**Comment by bjnortier** [comment]
Closing this since interpolate.js no longer exists, please create a new issue if you think some functions should still be exposed 👍🏻
