### ISSUE TITLE
NPM code and GitHub are out of sync

### ISSUE THREAD

**Issue by zzz0908** [bjnortier/dxf#94]
NPM code error

**Comment by skymakerolof** [comment]
Hi @zzz0908, thank you for reaching out! Do you mean that the link on npm is to https://github.com/bjnortier/dxf while the repository now is located at https://github.com/skymakerolof/dxf? Seems like github handles this redirect gracefully, but I will update package.json to reflect this change as well, so it should be resolved with the next release to npm.
